import type { TcgSet } from '../types'

// Snapshot of GET /v2/sets taken on 2026-10-08. Used only as a fallback when the
// live /sets request fails (the API often answers 500/502); sets released later are missing.
export const SETS_SNAPSHOT: TcgSet[] = [
  {"id": "base1", "name": "Base", "series": "Base", "releaseDate": "1999/01/09", "ptcgoCode": "BS"},
  {"id": "base2", "name": "Jungle", "series": "Base", "releaseDate": "1999/06/16", "ptcgoCode": "JU"},
  {"id": "basep", "name": "Wizards Black Star Promos", "series": "Base", "releaseDate": "1999/07/01", "ptcgoCode": "PR"},
  {"id": "base3", "name": "Fossil", "series": "Base", "releaseDate": "1999/10/10", "ptcgoCode": "FO"},
  {"id": "base4", "name": "Base Set 2", "series": "Base", "releaseDate": "2000/02/24", "ptcgoCode": "B2"},
  {"id": "base5", "name": "Team Rocket", "series": "Base", "releaseDate": "2000/04/24", "ptcgoCode": "TR"},
  {"id": "gym1", "name": "Gym Heroes", "series": "Gym", "releaseDate": "2000/08/14", "ptcgoCode": "G1"},
  {"id": "gym2", "name": "Gym Challenge", "series": "Gym", "releaseDate": "2000/10/16", "ptcgoCode": "G2"},
  {"id": "neo1", "name": "Neo Genesis", "series": "Neo", "releaseDate": "2000/12/16", "ptcgoCode": "N1"},
  {"id": "neo2", "name": "Neo Discovery", "series": "Neo", "releaseDate": "2001/06/01", "ptcgoCode": "N2"},
  {"id": "si1", "name": "Southern Islands", "series": "Other", "releaseDate": "2001/07/31"},
  {"id": "neo3", "name": "Neo Revelation", "series": "Neo", "releaseDate": "2001/09/21", "ptcgoCode": "N3"},
  {"id": "neo4", "name": "Neo Destiny", "series": "Neo", "releaseDate": "2002/02/28", "ptcgoCode": "N4"},
  {"id": "base6", "name": "Legendary Collection", "series": "Other", "releaseDate": "2002/05/24", "ptcgoCode": "LC"},
  {"id": "ecard1", "name": "Expedition Base Set", "series": "E-Card", "releaseDate": "2002/09/15", "ptcgoCode": "EX"},
  {"id": "bp", "name": "Best of Game", "series": "Other", "releaseDate": "2002/12/01", "ptcgoCode": "BP"},
  {"id": "ecard2", "name": "Aquapolis", "series": "E-Card", "releaseDate": "2003/01/15", "ptcgoCode": "AQ"},
  {"id": "ecard3", "name": "Skyridge", "series": "E-Card", "releaseDate": "2003/05/12", "ptcgoCode": "SK"},
  {"id": "ex1", "name": "Ruby & Sapphire", "series": "EX", "releaseDate": "2003/07/01", "ptcgoCode": "RS"},
  {"id": "ex2", "name": "Sandstorm", "series": "EX", "releaseDate": "2003/09/18", "ptcgoCode": "SS"},
  {"id": "np", "name": "Nintendo Black Star Promos", "series": "NP", "releaseDate": "2003/10/01", "ptcgoCode": "PR-NP"},
  {"id": "ex3", "name": "Dragon", "series": "EX", "releaseDate": "2003/11/24", "ptcgoCode": "DR"},
  {"id": "ex4", "name": "Team Magma vs Team Aqua", "series": "EX", "releaseDate": "2004/03/01", "ptcgoCode": "MA"},
  {"id": "ex5", "name": "Hidden Legends", "series": "EX", "releaseDate": "2004/06/01", "ptcgoCode": "HL"},
  {"id": "tk1a", "name": "EX Trainer Kit Latias", "series": "EX", "releaseDate": "2004/06/01"},
  {"id": "tk1b", "name": "EX Trainer Kit Latios", "series": "EX", "releaseDate": "2004/06/01"},
  {"id": "ex6", "name": "FireRed & LeafGreen", "series": "EX", "releaseDate": "2004/09/01", "ptcgoCode": "RG"},
  {"id": "pop1", "name": "POP Series 1", "series": "POP", "releaseDate": "2004/09/01"},
  {"id": "ex7", "name": "Team Rocket Returns", "series": "EX", "releaseDate": "2004/11/01", "ptcgoCode": "TRR"},
  {"id": "ex8", "name": "Deoxys", "series": "EX", "releaseDate": "2005/02/01", "ptcgoCode": "DX"},
  {"id": "ex9", "name": "Emerald", "series": "EX", "releaseDate": "2005/05/01", "ptcgoCode": "EM"},
  {"id": "ex10", "name": "Unseen Forces", "series": "EX", "releaseDate": "2005/08/01", "ptcgoCode": "UF"},
  {"id": "pop2", "name": "POP Series 2", "series": "POP", "releaseDate": "2005/08/01"},
  {"id": "ex11", "name": "Delta Species", "series": "EX", "releaseDate": "2005/10/31", "ptcgoCode": "DS"},
  {"id": "ex12", "name": "Legend Maker", "series": "EX", "releaseDate": "2006/02/01", "ptcgoCode": "LM"},
  {"id": "tk2a", "name": "EX Trainer Kit 2 Plusle", "series": "EX", "releaseDate": "2006/03/01"},
  {"id": "tk2b", "name": "EX Trainer Kit 2 Minun", "series": "EX", "releaseDate": "2006/03/01"},
  {"id": "pop3", "name": "POP Series 3", "series": "POP", "releaseDate": "2006/04/01"},
  {"id": "ex13", "name": "Holon Phantoms", "series": "EX", "releaseDate": "2006/05/01", "ptcgoCode": "HP"},
  {"id": "ex14", "name": "Crystal Guardians", "series": "EX", "releaseDate": "2006/08/01", "ptcgoCode": "CG"},
  {"id": "pop4", "name": "POP Series 4", "series": "POP", "releaseDate": "2006/08/01"},
  {"id": "ex15", "name": "Dragon Frontiers", "series": "EX", "releaseDate": "2006/11/01", "ptcgoCode": "DF"},
  {"id": "ex16", "name": "Power Keepers", "series": "EX", "releaseDate": "2007/02/02", "ptcgoCode": "PK"},
  {"id": "pop5", "name": "POP Series 5", "series": "POP", "releaseDate": "2007/03/01"},
  {"id": "dp1", "name": "Diamond & Pearl", "series": "Diamond & Pearl", "releaseDate": "2007/05/01", "ptcgoCode": "DP"},
  {"id": "dpp", "name": "DP Black Star Promos", "series": "Diamond & Pearl", "releaseDate": "2007/05/01", "ptcgoCode": "PR-DPP"},
  {"id": "dp2", "name": "Mysterious Treasures", "series": "Diamond & Pearl", "releaseDate": "2007/08/01", "ptcgoCode": "MT"},
  {"id": "pop6", "name": "POP Series 6", "series": "POP", "releaseDate": "2007/09/01"},
  {"id": "dp3", "name": "Secret Wonders", "series": "Diamond & Pearl", "releaseDate": "2007/11/01", "ptcgoCode": "SW"},
  {"id": "dp4", "name": "Great Encounters", "series": "Diamond & Pearl", "releaseDate": "2008/02/01", "ptcgoCode": "GE"},
  {"id": "pop7", "name": "POP Series 7", "series": "POP", "releaseDate": "2008/03/01"},
  {"id": "dp5", "name": "Majestic Dawn", "series": "Diamond & Pearl", "releaseDate": "2008/05/01", "ptcgoCode": "MD"},
  {"id": "dp6", "name": "Legends Awakened", "series": "Diamond & Pearl", "releaseDate": "2008/08/01", "ptcgoCode": "LA"},
  {"id": "pop8", "name": "POP Series 8", "series": "POP", "releaseDate": "2008/09/01"},
  {"id": "dp7", "name": "Stormfront", "series": "Diamond & Pearl", "releaseDate": "2008/11/01", "ptcgoCode": "SF"},
  {"id": "pl1", "name": "Platinum", "series": "Platinum", "releaseDate": "2009/02/11", "ptcgoCode": "PL"},
  {"id": "pop9", "name": "POP Series 9", "series": "POP", "releaseDate": "2009/03/01"},
  {"id": "pl2", "name": "Rising Rivals", "series": "Platinum", "releaseDate": "2009/05/16", "ptcgoCode": "RR"},
  {"id": "pl3", "name": "Supreme Victors", "series": "Platinum", "releaseDate": "2009/08/19", "ptcgoCode": "SV"},
  {"id": "pl4", "name": "Arceus", "series": "Platinum", "releaseDate": "2009/11/04", "ptcgoCode": "AR"},
  {"id": "ru1", "name": "Pokémon Rumble", "series": "Other", "releaseDate": "2009/12/02"},
  {"id": "hgss1", "name": "HeartGold & SoulSilver", "series": "HeartGold & SoulSilver", "releaseDate": "2010/02/10", "ptcgoCode": "HS"},
  {"id": "hsp", "name": "HGSS Black Star Promos", "series": "HeartGold & SoulSilver", "releaseDate": "2010/02/10", "ptcgoCode": "PR-HS"},
  {"id": "hgss2", "name": "HS—Unleashed", "series": "HeartGold & SoulSilver", "releaseDate": "2010/05/12", "ptcgoCode": "UL"},
  {"id": "hgss3", "name": "HS—Undaunted", "series": "HeartGold & SoulSilver", "releaseDate": "2010/08/18", "ptcgoCode": "UD"},
  {"id": "hgss4", "name": "HS—Triumphant", "series": "HeartGold & SoulSilver", "releaseDate": "2010/11/03", "ptcgoCode": "TM"},
  {"id": "col1", "name": "Call of Legends", "series": "HeartGold & SoulSilver", "releaseDate": "2011/02/09", "ptcgoCode": "CL"},
  {"id": "bwp", "name": "BW Black Star Promos", "series": "Black & White", "releaseDate": "2011/03/01", "ptcgoCode": "PR-BLW"},
  {"id": "bw1", "name": "Black & White", "series": "Black & White", "releaseDate": "2011/04/25", "ptcgoCode": "BLW"},
  {"id": "mcd11", "name": "McDonald's Collection 2011", "series": "Other", "releaseDate": "2011/06/17"},
  {"id": "bw2", "name": "Emerging Powers", "series": "Black & White", "releaseDate": "2011/08/31", "ptcgoCode": "EPO"},
  {"id": "bw3", "name": "Noble Victories", "series": "Black & White", "releaseDate": "2011/11/16", "ptcgoCode": "NVI"},
  {"id": "bw4", "name": "Next Destinies", "series": "Black & White", "releaseDate": "2012/02/08", "ptcgoCode": "NXD"},
  {"id": "bw5", "name": "Dark Explorers", "series": "Black & White", "releaseDate": "2012/05/09", "ptcgoCode": "DEX"},
  {"id": "mcd12", "name": "McDonald's Collection 2012", "series": "Other", "releaseDate": "2012/06/15"},
  {"id": "bw6", "name": "Dragons Exalted", "series": "Black & White", "releaseDate": "2012/08/15", "ptcgoCode": "DRX"},
  {"id": "dv1", "name": "Dragon Vault", "series": "Black & White", "releaseDate": "2012/10/05", "ptcgoCode": "DRV"},
  {"id": "bw7", "name": "Boundaries Crossed", "series": "Black & White", "releaseDate": "2012/11/07", "ptcgoCode": "BCR"},
  {"id": "bw8", "name": "Plasma Storm", "series": "Black & White", "releaseDate": "2013/02/06", "ptcgoCode": "PLS"},
  {"id": "bw9", "name": "Plasma Freeze", "series": "Black & White", "releaseDate": "2013/05/08", "ptcgoCode": "PLF"},
  {"id": "bw10", "name": "Plasma Blast", "series": "Black & White", "releaseDate": "2013/08/14", "ptcgoCode": "PLB"},
  {"id": "xyp", "name": "XY Black Star Promos", "series": "XY", "releaseDate": "2013/10/12", "ptcgoCode": "PR-XY"},
  {"id": "bw11", "name": "Legendary Treasures", "series": "Black & White", "releaseDate": "2013/11/06", "ptcgoCode": "LTR"},
  {"id": "xy0", "name": "Kalos Starter Set", "series": "XY", "releaseDate": "2013/11/08", "ptcgoCode": "KSS"},
  {"id": "xy1", "name": "XY", "series": "XY", "releaseDate": "2014/02/05", "ptcgoCode": "XY"},
  {"id": "xy2", "name": "Flashfire", "series": "XY", "releaseDate": "2014/05/07", "ptcgoCode": "FLF"},
  {"id": "mcd14", "name": "McDonald's Collection 2014", "series": "Other", "releaseDate": "2014/05/23"},
  {"id": "xy3", "name": "Furious Fists", "series": "XY", "releaseDate": "2014/08/13", "ptcgoCode": "FFI"},
  {"id": "xy4", "name": "Phantom Forces", "series": "XY", "releaseDate": "2014/11/05", "ptcgoCode": "PHF"},
  {"id": "xy5", "name": "Primal Clash", "series": "XY", "releaseDate": "2015/02/04", "ptcgoCode": "PRC"},
  {"id": "dc1", "name": "Double Crisis", "series": "XY", "releaseDate": "2015/03/25", "ptcgoCode": "DCR"},
  {"id": "xy6", "name": "Roaring Skies", "series": "XY", "releaseDate": "2015/05/06", "ptcgoCode": "ROS"},
  {"id": "xy7", "name": "Ancient Origins", "series": "XY", "releaseDate": "2015/08/12", "ptcgoCode": "AOR"},
  {"id": "xy8", "name": "BREAKthrough", "series": "XY", "releaseDate": "2015/11/04", "ptcgoCode": "BKT"},
  {"id": "mcd15", "name": "McDonald's Collection 2015", "series": "Other", "releaseDate": "2015/11/27"},
  {"id": "xy9", "name": "BREAKpoint", "series": "XY", "releaseDate": "2016/02/03", "ptcgoCode": "BKP"},
  {"id": "g1", "name": "Generations", "series": "XY", "releaseDate": "2016/02/22", "ptcgoCode": "GEN"},
  {"id": "xy10", "name": "Fates Collide", "series": "XY", "releaseDate": "2016/05/02", "ptcgoCode": "FCO"},
  {"id": "xy11", "name": "Steam Siege", "series": "XY", "releaseDate": "2016/08/03", "ptcgoCode": "STS"},
  {"id": "mcd16", "name": "McDonald's Collection 2016", "series": "Other", "releaseDate": "2016/08/19"},
  {"id": "xy12", "name": "Evolutions", "series": "XY", "releaseDate": "2016/11/02", "ptcgoCode": "EVO"},
  {"id": "sm1", "name": "Sun & Moon", "series": "Sun & Moon", "releaseDate": "2017/02/03", "ptcgoCode": "SUM"},
  {"id": "smp", "name": "SM Black Star Promos", "series": "Sun & Moon", "releaseDate": "2017/02/03", "ptcgoCode": "PR-SM"},
  {"id": "sm2", "name": "Guardians Rising", "series": "Sun & Moon", "releaseDate": "2017/05/05", "ptcgoCode": "GRI"},
  {"id": "sm3", "name": "Burning Shadows", "series": "Sun & Moon", "releaseDate": "2017/08/05", "ptcgoCode": "BUS"},
  {"id": "sm35", "name": "Shining Legends", "series": "Sun & Moon", "releaseDate": "2017/10/06", "ptcgoCode": "SLG"},
  {"id": "sm4", "name": "Crimson Invasion", "series": "Sun & Moon", "releaseDate": "2017/11/03", "ptcgoCode": "CIN"},
  {"id": "mcd17", "name": "McDonald's Collection 2017", "series": "Other", "releaseDate": "2017/11/07"},
  {"id": "sm5", "name": "Ultra Prism", "series": "Sun & Moon", "releaseDate": "2018/02/02", "ptcgoCode": "UPR"},
  {"id": "sm6", "name": "Forbidden Light", "series": "Sun & Moon", "releaseDate": "2018/05/04", "ptcgoCode": "FLI"},
  {"id": "sm7", "name": "Celestial Storm", "series": "Sun & Moon", "releaseDate": "2018/08/03", "ptcgoCode": "CES"},
  {"id": "sm75", "name": "Dragon Majesty", "series": "Sun & Moon", "releaseDate": "2018/09/07", "ptcgoCode": "DRM"},
  {"id": "mcd18", "name": "McDonald's Collection 2018", "series": "Other", "releaseDate": "2018/10/16"},
  {"id": "sm8", "name": "Lost Thunder", "series": "Sun & Moon", "releaseDate": "2018/11/02", "ptcgoCode": "LOT"},
  {"id": "sm9", "name": "Team Up", "series": "Sun & Moon", "releaseDate": "2019/02/01", "ptcgoCode": "TEU"},
  {"id": "det1", "name": "Detective Pikachu", "series": "Sun & Moon", "releaseDate": "2019/04/05", "ptcgoCode": "DET"},
  {"id": "sm10", "name": "Unbroken Bonds", "series": "Sun & Moon", "releaseDate": "2019/05/03", "ptcgoCode": "UNB"},
  {"id": "sm11", "name": "Unified Minds", "series": "Sun & Moon", "releaseDate": "2019/08/02", "ptcgoCode": "UNM"},
  {"id": "sm115", "name": "Hidden Fates", "series": "Sun & Moon", "releaseDate": "2019/08/23", "ptcgoCode": "HIF"},
  {"id": "sma", "name": "Hidden Fates Shiny Vault", "series": "Sun & Moon", "releaseDate": "2019/08/23", "ptcgoCode": "HIF"},
  {"id": "mcd19", "name": "McDonald's Collection 2019", "series": "Other", "releaseDate": "2019/10/15"},
  {"id": "sm12", "name": "Cosmic Eclipse", "series": "Sun & Moon", "releaseDate": "2019/11/01", "ptcgoCode": "CEC"},
  {"id": "swshp", "name": "SWSH Black Star Promos", "series": "Sword & Shield", "releaseDate": "2019/11/15", "ptcgoCode": "PR-SW"},
  {"id": "swsh1", "name": "Sword & Shield", "series": "Sword & Shield", "releaseDate": "2020/02/07", "ptcgoCode": "SSH"},
  {"id": "swsh2", "name": "Rebel Clash", "series": "Sword & Shield", "releaseDate": "2020/05/01", "ptcgoCode": "RCL"},
  {"id": "swsh3", "name": "Darkness Ablaze", "series": "Sword & Shield", "releaseDate": "2020/08/14", "ptcgoCode": "DAA"},
  {"id": "fut20", "name": "Pokémon Futsal Collection", "series": "Other", "releaseDate": "2020/09/11", "ptcgoCode": "FUT20"},
  {"id": "swsh35", "name": "Champion's Path", "series": "Sword & Shield", "releaseDate": "2020/09/25", "ptcgoCode": "CPA"},
  {"id": "swsh4", "name": "Vivid Voltage", "series": "Sword & Shield", "releaseDate": "2020/11/13", "ptcgoCode": "VIV"},
  {"id": "mcd21", "name": "McDonald's Collection 2021", "series": "Other", "releaseDate": "2021/02/09"},
  {"id": "swsh45", "name": "Shining Fates", "series": "Sword & Shield", "releaseDate": "2021/02/19", "ptcgoCode": "SHF"},
  {"id": "swsh45sv", "name": "Shining Fates Shiny Vault", "series": "Sword & Shield", "releaseDate": "2021/02/19", "ptcgoCode": "SHF"},
  {"id": "swsh5", "name": "Battle Styles", "series": "Sword & Shield", "releaseDate": "2021/03/19", "ptcgoCode": "BST"},
  {"id": "swsh6", "name": "Chilling Reign", "series": "Sword & Shield", "releaseDate": "2021/06/18", "ptcgoCode": "CRE"},
  {"id": "swsh7", "name": "Evolving Skies", "series": "Sword & Shield", "releaseDate": "2021/08/27", "ptcgoCode": "EVS"},
  {"id": "cel25", "name": "Celebrations", "series": "Sword & Shield", "releaseDate": "2021/10/08", "ptcgoCode": "CEL"},
  {"id": "cel25c", "name": "Celebrations: Classic Collection", "series": "Sword & Shield", "releaseDate": "2021/10/08", "ptcgoCode": "CEL"},
  {"id": "swsh8", "name": "Fusion Strike", "series": "Sword & Shield", "releaseDate": "2021/11/12", "ptcgoCode": "FST"},
  {"id": "swsh9", "name": "Brilliant Stars", "series": "Sword & Shield", "releaseDate": "2022/02/25", "ptcgoCode": "BRS"},
  {"id": "swsh9tg", "name": "Brilliant Stars Trainer Gallery", "series": "Sword & Shield", "releaseDate": "2022/02/25", "ptcgoCode": "BRS"},
  {"id": "swsh10", "name": "Astral Radiance", "series": "Sword & Shield", "releaseDate": "2022/05/27", "ptcgoCode": "ASR"},
  {"id": "swsh10tg", "name": "Astral Radiance Trainer Gallery", "series": "Sword & Shield", "releaseDate": "2022/05/27", "ptcgoCode": "ASR"},
  {"id": "pgo", "name": "Pokémon GO", "series": "Sword & Shield", "releaseDate": "2022/07/01", "ptcgoCode": "PGO"},
  {"id": "mcd22", "name": "McDonald's Collection 2022", "series": "Other", "releaseDate": "2022/08/03"},
  {"id": "swsh11", "name": "Lost Origin", "series": "Sword & Shield", "releaseDate": "2022/09/09", "ptcgoCode": "LOR"},
  {"id": "swsh11tg", "name": "Lost Origin Trainer Gallery", "series": "Sword & Shield", "releaseDate": "2022/09/09", "ptcgoCode": "LOR"},
  {"id": "swsh12", "name": "Silver Tempest", "series": "Sword & Shield", "releaseDate": "2022/11/11", "ptcgoCode": "SIT"},
  {"id": "swsh12tg", "name": "Silver Tempest Trainer Gallery", "series": "Sword & Shield", "releaseDate": "2022/11/11", "ptcgoCode": "SIT"},
  {"id": "svp", "name": "Scarlet & Violet Black Star Promos", "series": "Scarlet & Violet", "releaseDate": "2023/01/01", "ptcgoCode": "PR-SV"},
  {"id": "swsh12pt5", "name": "Crown Zenith", "series": "Sword & Shield", "releaseDate": "2023/01/20", "ptcgoCode": "CRZ"},
  {"id": "swsh12pt5gg", "name": "Crown Zenith Galarian Gallery", "series": "Sword & Shield", "releaseDate": "2023/01/20", "ptcgoCode": "CRZ"},
  {"id": "sv1", "name": "Scarlet & Violet", "series": "Scarlet & Violet", "releaseDate": "2023/03/31", "ptcgoCode": "SVI"},
  {"id": "sve", "name": "Scarlet & Violet Energies", "series": "Scarlet & Violet", "releaseDate": "2023/03/31", "ptcgoCode": "SVE"},
  {"id": "sv2", "name": "Paldea Evolved", "series": "Scarlet & Violet", "releaseDate": "2023/06/09", "ptcgoCode": "PAL"},
  {"id": "sv3", "name": "Obsidian Flames", "series": "Scarlet & Violet", "releaseDate": "2023/08/11", "ptcgoCode": "OBF"},
  {"id": "sv3pt5", "name": "151", "series": "Scarlet & Violet", "releaseDate": "2023/09/22", "ptcgoCode": "MEW"},
  {"id": "sv4", "name": "Paradox Rift", "series": "Scarlet & Violet", "releaseDate": "2023/11/03", "ptcgoCode": "PAR"},
  {"id": "sv4pt5", "name": "Paldean Fates", "series": "Scarlet & Violet", "releaseDate": "2024/01/26", "ptcgoCode": "PAF"},
  {"id": "sv5", "name": "Temporal Forces", "series": "Scarlet & Violet", "releaseDate": "2024/03/22", "ptcgoCode": "TEF"},
  {"id": "sv6", "name": "Twilight Masquerade", "series": "Scarlet & Violet", "releaseDate": "2024/05/24", "ptcgoCode": "TWM"},
  {"id": "sv6pt5", "name": "Shrouded Fable", "series": "Scarlet & Violet", "releaseDate": "2024/08/02", "ptcgoCode": "SFA"},
  {"id": "sv7", "name": "Stellar Crown", "series": "Scarlet & Violet", "releaseDate": "2024/09/13", "ptcgoCode": "SCR"},
  {"id": "sv8", "name": "Surging Sparks", "series": "Scarlet & Violet", "releaseDate": "2024/11/08", "ptcgoCode": "SSP"},
  {"id": "sv8pt5", "name": "Prismatic Evolutions", "series": "Scarlet & Violet", "releaseDate": "2025/01/17", "ptcgoCode": "PRE"},
  {"id": "sv9", "name": "Journey Together", "series": "Scarlet & Violet", "releaseDate": "2025/03/28", "ptcgoCode": "JTG"},
  {"id": "sv10", "name": "Destined Rivals", "series": "Scarlet & Violet", "releaseDate": "2025/05/30", "ptcgoCode": "DRI"},
  {"id": "rsv10pt5", "name": "White Flare", "series": "Scarlet & Violet", "releaseDate": "2025/07/18", "ptcgoCode": "WHT"},
  {"id": "zsv10pt5", "name": "Black Bolt", "series": "Scarlet & Violet", "releaseDate": "2025/07/18", "ptcgoCode": "BLK"},
  {"id": "me1", "name": "Mega Evolution", "series": "Mega Evolution", "releaseDate": "2025/09/26", "ptcgoCode": "MEG"},
  {"id": "me2", "name": "Phantasmal Flames", "series": "Mega Evolution", "releaseDate": "2025/11/14", "ptcgoCode": "PFL"},
  {"id": "me2pt5", "name": "Ascended Heroes", "series": "Mega Evolution", "releaseDate": "2026/01/30", "ptcgoCode": "ASC"},
  {"id": "me3", "name": "Perfect Order", "series": "Mega Evolution", "releaseDate": "2026/03/27", "ptcgoCode": "POR"},
  {"id": "me4", "name": "Chaos Rising", "series": "Mega Evolution", "releaseDate": "2026/05/22", "ptcgoCode": "CRI"},
  {"id": "me5", "name": "Pitch Black", "series": "Mega Evolution", "releaseDate": "2026/07/17", "ptcgoCode": "PBL"},
  {"id": "me55", "name": "30th Celebration", "series": "Mega Evolution", "releaseDate": "2026/09/16", "ptcgoCode": "30C"},
  {"id": "me55c", "name": "30th Celebration: Classic Collection", "series": "Mega Evolution", "releaseDate": "2026/09/16", "ptcgoCode": "30C"},
]
